### ISSUE TITLE
PyMallet much slower than Java Mallet

### ISSUE THREAD

**Issue by gtsherman** [mimno/PyMallet#2]
I've been doing some experiments with PyMallet against Java Mallet, and I'm surprised at the difference in compute time. On the same data set with the same hyperparameters, I found that Mallet (with one thread) takes ~80 minutes while PyMallet takes ~260 minutes. This seems surprising since PyMallet uses Cython. I've confirmed `topicmodel.pyx` is compiled. Any idea what I might be missing that would cause this difference in speed?

**Comment by mimno** [comment]
There are several tricks that Java Mallet does related to sparse sampling that are not implemented in PyMallet. For example, doubling the number of topics will double the time for PyMallet, but only slightly increase for Java Mallet. But it's much, much faster than a comparable pure-Python implementation! The goal of this package is to provide a sampling-based implementation that isn't terrible that doesn't require Java.

**Comment by gtsherman** [comment]
That makes sense! I'm glad to hear I'm not doing anything wrong. Thanks for your reply and for making PyMallet!
